baseURL = "http://amasucci.com/"
languageCode = "en-us"
title = "amasucci's blog"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
    name = "about me"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
[permalinks]
  post = "/post/:year/:month/:day/:slug/"
  project = "/project/:year/:month/:day/:slug/"

[indexes]
  tag = "tags"
  topic = "topics"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[params]
  # Warning Keys are case sensitives
  Subtitle = "blog"
  description = "Developer technologist"
  cover = "/img/sfondo.png"

  # Google analytics
  googleAnalyticsUserID = "UA-75901778-2"
  googleAdsenseID = "ca-pub-6496372850821508"
  disqus = "amasucci-com"

  [params.author]
    firstName = "Antonio"
    lastName = "Masucci"
    gender = "male"
    userName = "amasucci"
    image = "//www.gravatar.com/avatar/3f4b8490a22178512e78087a1d53e9ee.png"
    website = "http://amasucci.com/"
    twitter = "_amasucci_"
    github = "amasucci"
    facebook = "xxxxxxxxx"
    linkedin = "xxxxxxxxx"
    gplus = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    gravatarHash = "3f4b8490a22178512e78087a1d53e9ee"
